In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline 

In [2]:
file = pd.read_csv('marketing_customer_analysis.csv')
file.shape

(9134, 24)

In [ ]:
file.head()

In [ ]:
file = file.drop(['Unnamed: 0'], axis=1)
file = file.rename(columns={'EmploymentStatus':'Employment Status'})

In [ ]:
file.head()

In [ ]:
file.dtypes

In [ ]:
file.select_dtypes('number')

In [ ]:
file.select_dtypes('object')

In [ ]:
#Numerical columns: Customer Lifetime Value, Income, Monthly Premium Auto,Months Since Last Claim, Months Since Policy Inception, Number of Open Complaints, Number of Policies, Total Claim Amount 
#Categorical columns: State, Coverage, Education, Employment Status, Gender, Policy Type, Policy, Renew Offer Type, Sales Channel, Vehicle Class, Vehicle Size, Vehicle Type   


In [ ]:
file.isna().sum()

In [ ]:
#Months Since Last Claim: I've decided to do the mean of the rest of the values
mean_Months_Since_Last_Claim = file['Months Since Last Claim'].mean()
mean_Months_Since_Last_Claim
file['Months Since Last Claim'] = file['Months Since Last Claim'].fillna(mean_Months_Since_Last_Claim)

In [ ]:
#Number of complaints: I've decided to take the median because the range of values was very short
median_Num_Com = file['Number of Open Complaints'].median()
median_Num_Com
file['Number of Open Complaints'] = file['Number of Open Complaints'].fillna(median_Num_Com)



In [ ]:
#Response: I've decided to use the most common value
file['Response'].unique()
file['Response'].value_counts()

In [ ]:
file['Response'] = file['Response'].fillna('No')

In [ ]:
file['Vehicle Class'].unique()
file['Vehicle Class'].value_counts()

In [ ]:
#Vehicle Class: I've decided to use the most common value because it represents more than the 50% of the answers
file['Vehicle Class'] = file['Vehicle Class'].fillna('Four-Door Car')

In [ ]:
file['Vehicle Size'].unique()
file['Vehicle Size'].value_counts()

In [ ]:
#Vehicle Size: again, I've decided to use the most common value because it represents more than the 50% of the answers
file['Vehicle Size'] = file['Vehicle Size'].fillna('Medsize')

In [ ]:
file['State'].unique()
file['State'].value_counts()

In [ ]:
#Because I am not able to know the State and there are several options 
#I've decided to writte Unknown
file['State'] = file['State'].fillna('Unknown')

In [ ]:
file['Vehicle Type'].unique()
file['Vehicle Type'].value_counts()

In [ ]:
#Finally, I've decided to eliminate Vehicle Type because half of them are A
#and the other half are NaN so it is irrelevant
file = file.drop(['Vehicle Type'], axis=1)


In [ ]:
file.isna().sum()

In [ ]:
#file['Effective To Date'] = pd.to_datetime(file['Effective To Date']
#file['Month'] = file['Effective To Date'].dt.month
#Last two lines do the same as the following function:
def ExtractMonth(file):
    file_dt = pd.to_datetime(file)
    file_m = file_dt.dt.month
    return file_m
file['Month'] = ExtractMonth(file['Effective To Date'])

In [ ]:
file.head()

In [ ]:
file['Month'].unique()
file['Month'].value_counts()

In [ ]:
#I will only filter the january and february data because march data do not exist
#but, as we have seen before, I will obtain all the values because they are only 1 and 2
file[(file['Month']==1) | (file['Month']==2) ]


In [ ]:
#Lab | Customer Analysis Round 3

In [ ]:
file.shape

In [ ]:
file.head()

In [ ]:
file.dtypes

In [ ]:
#Looking at the information we have above, I can say we have a dataframe with 25 columns which contain different type
#of data related with the clients of a cars insurance company 
#Customer: client code
#State: client state
#Customer Lifetime Value: the value that the client has for the company
#Response: if the client has it or not
#Coverage: type of coverage
#Education: grade of education
#Effective To Date: end date of the coverage
#Employment Status: if the client is working
#Gender: client gender
#Income: amount of income
#Location Code: code of the client location
#Marital Status: marital status of the client
#Monthly Premium Auto: premium payment amount
#Months Since Last Claim: months without claiming
#Months Since Policy Inception: months since the policy started
#Number of Open Complaints: Complaints that have not been solved
#Number of Policies: contracted policies
#Policy Type: type of policy that the client has 
#Policy: policy tipe code
#Renew Offer Type: offer offered to renew the policy
#Sales Channel: how the policy was sold
#Total Claim Amount: quantity of the claim required by the client
#Vehicle Class: type of the vehicle
#Vehicle Size: size of the vehicle
#Month: month extracted from the column: Effective To Date

In [ ]:
file['Response'].value_counts().plot(kind='bar', title='Response')
plt.show()

In [ ]:
plt.figure(figsize=(8,4))
sns.countplot('Sales Channel', hue='Response', data=file)
plt.ylabel('Response by Sales Channel')

In [ ]:
file_new = file
file_new['Response_Rate'] = np.where(file_new.Response=='Yes',1,0)

In [ ]:
file_new.Response_Rate.value_counts()

In [ ]:
file_new.groupby('Sales Channel')['Response_Rate'].mean().plot.bar()                                           
plt.show

In [ ]:
print(file_new['Total Claim Amount'].max())    
print(file_new['Total Claim Amount'].min())    
print(file_new['Total Claim Amount'].mean())                                      

In [ ]:
def TotCA_div(x):
    if x <= 450:
        return 1
    elif x <= 900:
        return 2
    elif x <= 1350:
        return 3
    elif x <= 1800:
        return 4
    else:
        return 5

file_new['Total Claim Amount_bins'] = list(map(TotCA_div, file_new['Total Claim Amount']))

In [ ]:
file_new.groupby('Total Claim Amount_bins')['Response_Rate'].mean().plot.bar()                                           
index = np.arange(5)
plt.xticks(index, ("0-450", "451-900", "901-1350", "1351-1800", ">1800"))  
plt.show

In [ ]:
print(file_new['Income'].max())    
print(file_new['Income'].min())    
print(file_new['Income'].mean())

In [ ]:
def TotIn_div(x):
    if x <= 19000:
        return 1
    elif x <= 38000:
        return 2
    elif x <= 57000:
        return 3
    elif x <= 76000:
        return 4
    else:
        return 5

file_new['Income_bins'] = list(map(TotIn_div, file_new['Income']))

In [ ]:
file_new.groupby('Income_bins')['Response_Rate'].mean().plot.bar()
index = np.arange(5)
plt.xticks(index, ("0-19000", "19001-38000", "38001-57000", "57001-76000", ">76000"))  
plt.show

In [ ]:
#Lab | Customer Analysis Round 4

In [ ]:
numerical = file.select_dtypes('number')
numerical.head()

In [ ]:
categorical = file.select_dtypes('object')
categorical.head()

In [ ]:
sns.displot(file['Customer Lifetime Value'], bins=30)
plt.show()

In [ ]:
sns.displot(file['Income'], bins=30)
plt.show()

In [ ]:
sns.displot(file['Monthly Premium Auto'], bins=30)
plt.show()

In [ ]:
sns.displot(file['Months Since Last Claim'], bins=20)
plt.show()

In [ ]:
sns.displot(file['Months Since Policy Inception'], bins=20)
plt.show()

In [ ]:
sns.displot(file['Number of Open Complaints'], bins=6)
plt.show()

In [ ]:
sns.displot(file['Number of Policies'], bins=9)
plt.show()

In [ ]:
sns.displot(file['Total Claim Amount'], bins=50)
plt.show()

In [ ]:
#Total Claim Amount could look like a normal distribution

In [ ]:
correlations_matrix = file.corr()
sns.heatmap(correlations_matrix, annot=True)
plt.show()

In [ ]:
#I will drop no features because there is no pair of 
#features that have a high correlation 

In [ ]:
#Lab | Customer Analysis Round 5

In [ ]:
#Target variable: total_claim_amount

In [ ]:
display(file.head())
file.shape

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

y = file['Total Claim Amount']
X = file.drop(['Total Claim Amount'], axis=1)
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [ ]:
X_num

In [ ]:
#MinMaxScaler
transformer = MinMaxScaler().fit(X_num)
x_normalized = transformer.transform(X_num)
print(x_normalized.shape)
x_normalized
fileMinMax = pd.DataFrame(x_normalized, columns=X_num.columns)
fileMinMax.head()

In [ ]:
#StandardScaler
transformer = StandardScaler().fit(X_num)
x_standardized = transformer.transform(X_num)
print(x_standardized.shape)
fileStSc = pd.DataFrame(x_standardized, columns=X_num.columns)
fileStSc.head()

In [ ]:
sns.displot(fileMinMax['Customer Lifetime Value'], bins=50)
print(plt.show())
sns.displot(fileStSc['Customer Lifetime Value'], bins=50)
plt.show()

In [ ]:
sns.displot(fileMinMax['Income'], bins=50)
print(plt.show())
sns.displot(fileStSc['Income'], bins=50)
plt.show()

In [ ]:
sns.displot(fileMinMax['Monthly Premium Auto'], bins=50)
print(plt.show())
sns.displot(fileStSc['Monthly Premium Auto'], bins=50)
plt.show()

In [ ]:
sns.displot(fileMinMax['Months Since Last Claim'], bins=50)
print(plt.show())
sns.displot(fileStSc['Months Since Last Claim'], bins=50)
plt.show()

In [ ]:
sns.displot(fileMinMax['Months Since Policy Inception'], bins=50)
print(plt.show())
sns.displot(fileStSc['Months Since Policy Inception'], bins=50)
plt.show()

In [ ]:
sns.displot(fileMinMax['Number of Open Complaints'], bins=20)
print(plt.show())
sns.displot(fileStSc['Number of Open Complaints'], bins=20)
plt.show()

In [ ]:
sns.displot(fileMinMax['Number of Policies'], bins=20)
print(plt.show())
sns.displot(fileStSc['Number of Policies'], bins=20)
plt.show()

In [ ]:
#As we can observe in the graphics, the difference between both scalers is almost inexistent

In [ ]:
#Lab | Customer Analysis Round 6

In [3]:
y = file['Total Claim Amount']
X = file.drop(['Total Claim Amount'], axis=1)
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [4]:
#Faster way to do it

In [5]:
#Searching on google, I found the next way to simplificate One Hot encoding with the command pd.get_dummies: 
#https://datascience.stackexchange.com/questions/71804/how-to-perform-one-hot-encoding-on-multiple-categorical-columns
flags_ohe = X
categorical_columns = file[X_cat.columns]

for col in categorical_columns:
    col_ohe = pd.get_dummies(file[col], prefix=col, drop_first=True) #drop_first=True -> to eliminate the first column (to avoid collinearity)
    flags_ohe = pd.concat((flags_ohe, col_ohe), axis=1).drop(col, axis=1)

flags_ohe.shape #flags_ohe would be the dataframe will all the numeric data and the categoric data encoded concatenated

(9134, 9241)

In [6]:
#Below, I'm goig to do it like we have seen in class!

In [7]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(X_num)
x_normalized = MinMaxtransformer.transform(X_num)
print(x_normalized.shape)
x_normalized = pd.DataFrame(x_normalized,columns=X_num.columns)

(9134, 7)


In [8]:
X_cat2 = X_cat[['Customer']]

In [9]:
#I'm going to use one hot encoding 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['AA10041', 'AA11235', 'AA16582', ..., 'ZZ89380', 'ZZ91716',
       'ZZ97035'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['AA10041'],axis=1)
X_new = pd.concat([x_normalized, onehot_encoded], axis=1)

In [11]:
X_cat2 = X_cat[['State']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Arizona', 'California', 'Nevada', 'Oregon', 'Washington'],
      dtype=object)]
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [12]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Arizona'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [13]:
X_cat2 = X_cat[['Response']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['No', 'Yes'], dtype=object)]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [14]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['No'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [15]:
X_cat2 = X_cat[['Coverage']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Basic', 'Extended', 'Premium'], dtype=object)]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [16]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Basic'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [17]:
X_cat2 = X_cat[['Education']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Bachelor', 'College', 'Doctor', 'High School or Below', 'Master'],
      dtype=object)]
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [18]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Bachelor'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [19]:
X_cat2 = X_cat[['Effective To Date']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['1/1/11', '1/10/11', '1/11/11', '1/12/11', '1/13/11', '1/14/11',
       '1/15/11', '1/16/11', '1/17/11', '1/18/11', '1/19/11', '1/2/11',
       '1/20/11', '1/21/11', '1/22/11', '1/23/11', '1/24/11', '1/25/11',
       '1/26/11', '1/27/11', '1/28/11', '1/29/11', '1/3/11', '1/30/11',
       '1/31/11', '1/4/11', '1/5/11', '1/6/11', '1/7/11', '1/8/11',
       '1/9/11', '2/1/11', '2/10/11', '2/11/11', '2/12/11', '2/13/11',
       '2/14/11', '2/15/11', '2/16/11', '2/17/11', '2/18/11', '2/19/11',
       '2/2/11', '2/20/11', '2/21/11', '2/22/11', '2/23/11', '2/24/11',
       '2/25/11', '2/26/11', '2/27/11', '2/28/11', '2/3/11', '2/4/11',
       '2/5/11', '2/6/11', '2/7/11', '2/8/11', '2/9/11'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['1/1/11'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [21]:
X_cat2 = X_cat[['EmploymentStatus']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Disabled', 'Employed', 'Medical Leave', 'Retired', 'Unemployed'],
      dtype=object)]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]


In [22]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Disabled'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [23]:
X_cat2 = X_cat[['Gender']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['F', 'M'], dtype=object)]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [24]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['F'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [25]:
X_cat2 = X_cat[['Location Code']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Rural', 'Suburban', 'Urban'], dtype=object)]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [26]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Rural'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [27]:
X_cat2 = X_cat[['Marital Status']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Divorced', 'Married', 'Single'], dtype=object)]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Divorced'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [29]:
X_cat2 = X_cat[['Policy Type']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Corporate Auto', 'Personal Auto', 'Special Auto'], dtype=object)]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [30]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Corporate Auto'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [31]:
X_cat2 = X_cat[['Policy']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Corporate L1', 'Corporate L2', 'Corporate L3', 'Personal L1',
       'Personal L2', 'Personal L3', 'Special L1', 'Special L2',
       'Special L3'], dtype=object)]
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [32]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Corporate L1'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [33]:
X_cat2 = X_cat[['Renew Offer Type']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Offer1', 'Offer2', 'Offer3', 'Offer4'], dtype=object)]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Offer1'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [35]:
X_cat2 = X_cat[['Sales Channel']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Agent', 'Branch', 'Call Center', 'Web'], dtype=object)]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [36]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Agent'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [37]:
X_cat2 = X_cat[['Vehicle Class']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Four-Door Car', 'Luxury Car', 'Luxury SUV', 'SUV', 'Sports Car',
       'Two-Door Car'], dtype=object)]
[[0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [38]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Four-Door Car'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [39]:
X_cat2 = X_cat[['Vehicle Size']]
encoder = OneHotEncoder().fit(X_cat2)
print(encoder.categories_)
encoded = encoder.transform(X_cat2).toarray()
print(encoded)
onehot_encoded = pd.DataFrame(encoded,columns=encoder.categories_)

[array(['Large', 'Medsize', 'Small'], dtype=object)]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [40]:
onehot_encoded = onehot_encoded.drop(onehot_encoded['Large'],axis=1)
X_new = pd.concat([X_new, onehot_encoded], axis=1)

In [41]:
X_new.shape

(9134, 9241)

In [42]:
#Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)


In [43]:
display(X_train.shape)
display(X_test.shape)
display(y_train.shape)
y_test.shape

(7307, 9241)

(1827, 9241)

(7307,)

(1827,)

In [44]:
#linear regression
from sklearn import linear_model
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [47]:
#Now I'll calculate R2 score, MSE, RMSE and MAE
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import math
predictions = lm.predict(X_train)
r2t = r2_score(y_train, predictions)
print("R2 for train:", r2t)
predictions = lm.predict(X_test)
r2s = r2_score(y_test, predictions)
print("R2 for score:", r2s)
mse = np.sqrt(mean_squared_error(y_test,predictions))
print("MSE:", mse)
rmse = math.sqrt(mse)
print("RMSE:", rmse)
mae = mean_absolute_error(y_test, predictions)
print("MAE:", mae)

R2 for train: 1.0
R2 for score: 0.7215960731645319
MSE: 148.7823443044834
RMSE: 12.197636832783774
MAE: 103.96029464044186


In [48]:
#Lab | Customer Analysis Round 7

In [49]:
#The first method I've tryed to improve the linear regression model consist on changing the test_size value,
#I've got the best results with test_size=0.5

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.5, random_state=42)
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [51]:
predictions = lm.predict(X_train)
r2t = r2_score(y_train, predictions)
print("R2 for train:", r2t)
predictions = lm.predict(X_test)
r2s = r2_score(y_test, predictions)
print("R2 for score:", r2s)
mse = np.sqrt(mean_squared_error(y_test,predictions))
print("MSE:", mse)
rmse = math.sqrt(mse)
print("RMSE:", rmse)
mae = mean_absolute_error(y_test, predictions)
print("MAE:", mae)

R2 for train: 1.0
R2 for score: 0.7651650741753026
MSE: 138.987179723224
RMSE: 11.789282409172493
MAE: 97.12474395990638


In [52]:
#Removing the outliers

In [53]:
iqr = np.percentile(file['Customer Lifetime Value'],75) - np.percentile(file['Customer Lifetime Value'],25)
upper_limit = np.percentile(file['Customer Lifetime Value'],75) + 1.5*iqr
lower_limit = np.percentile(file['Customer Lifetime Value'],25) - 1.5*iqr
file_without_O = file[(file['Customer Lifetime Value']>lower_limit) & (file['Customer Lifetime Value']<upper_limit)]

In [54]:
iqr = np.percentile(file['Income'],75) - np.percentile(file['Income'],25)
upper_limit = np.percentile(file['Income'],75) + 1.5*iqr
lower_limit = np.percentile(file['Income'],25) - 1.5*iqr
file_without_O = file[(file['Income']>lower_limit) & (file['Income']<upper_limit)]

In [55]:
iqr = np.percentile(file['Monthly Premium Auto'],75) - np.percentile(file['Monthly Premium Auto'],25)
upper_limit = np.percentile(file['Monthly Premium Auto'],75) + 1.5*iqr
lower_limit = np.percentile(file['Monthly Premium Auto'],25) - 1.5*iqr
file_without_O = file[(file['Monthly Premium Auto']>lower_limit) & (file['Monthly Premium Auto']<upper_limit)]

In [56]:
iqr = np.percentile(file['Months Since Last Claim'],75) - np.percentile(file['Months Since Last Claim'],25)
upper_limit = np.percentile(file['Months Since Last Claim'],75) + 1.5*iqr
lower_limit = np.percentile(file['Months Since Last Claim'],25) - 1.5*iqr
file_without_O = file[(file['Months Since Last Claim']>lower_limit) & (file['Months Since Last Claim']<upper_limit)]

In [57]:
iqr = np.percentile(file['Months Since Policy Inception'],75) - np.percentile(file['Months Since Policy Inception'],25)
upper_limit = np.percentile(file['Months Since Policy Inception'],75) + 1.5*iqr
lower_limit = np.percentile(file['Months Since Policy Inception'],25) - 1.5*iqr
file_without_O = file[(file['Months Since Policy Inception']>lower_limit) & (file['Months Since Policy Inception']<upper_limit)]

In [58]:
iqr = np.percentile(file['Number of Open Complaints'],75) - np.percentile(file['Number of Open Complaints'],25)
upper_limit = np.percentile(file['Number of Open Complaints'],75) + 1.5*iqr
lower_limit = np.percentile(file['Number of Open Complaints'],25) - 1.5*iqr
file_without_O = file[(file['Number of Open Complaints']>lower_limit) & (file['Number of Open Complaints']<upper_limit)]

In [59]:
iqr = np.percentile(file['Number of Policies'],75) - np.percentile(file['Number of Policies'],25)
upper_limit = np.percentile(file['Number of Policies'],75) + 1.5*iqr
lower_limit = np.percentile(file['Number of Policies'],25) - 1.5*iqr
file_without_O = file[(file['Number of Policies']>lower_limit) & (file['Number of Policies']<upper_limit)]

In [60]:
iqr = np.percentile(file['Total Claim Amount'],75) - np.percentile(file['Total Claim Amount'],25)
upper_limit = np.percentile(file['Total Claim Amount'],75) + 1.5*iqr
lower_limit = np.percentile(file['Total Claim Amount'],25) - 1.5*iqr
file_without_O = file[(file['Total Claim Amount']>lower_limit) & (file['Total Claim Amount']<upper_limit)]

In [61]:
display(file.shape)
file_without_O.shape

(9134, 24)

(8681, 24)

In [62]:
y = file_without_O['Total Claim Amount']
X = file_without_O.drop(['Total Claim Amount'], axis=1)
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [63]:
flags_ohe = X
categorical_columns = file_without_O[X_cat.columns]

for col in categorical_columns:
    col_ohe = pd.get_dummies(file_without_O[col], prefix=col, drop_first=True) #drop_first=True -> to eliminate the first column (to avoid collinearity)
    flags_ohe = pd.concat((flags_ohe, col_ohe), axis=1).drop(col, axis=1)

X_new = flags_ohe

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)

In [65]:
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [66]:
predictions = lm.predict(X_train)
r2t = r2_score(y_train, predictions)
print("R2 for train:", r2t)
predictions = lm.predict(X_test)
r2s = r2_score(y_test, predictions)
print("R2 for score:", r2s)
mse = np.sqrt(mean_squared_error(y_test,predictions))
print("MSE:", mse)
rmse = math.sqrt(mse)
print("RMSE:", rmse)
mae = mean_absolute_error(y_test, predictions)
print("MAE:", mae)

R2 for train: 1.0
R2 for score: 0.7839250795336019
MSE: 99.14783618837913
RMSE: 9.957300647684548
MAE: 76.33936349739184


In [67]:
#I'm going to check if this time the results are better with test_size=0.5

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.5, random_state=42)

In [69]:
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [70]:
predictions = lm.predict(X_train)
r2t = r2_score(y_train, predictions)
print("R2 for train:", r2t)
predictions = lm.predict(X_test)
r2s = r2_score(y_test, predictions)
print("R2 for score:", r2s)
mse = np.sqrt(mean_squared_error(y_test,predictions))
print("MSE:", mse)
rmse = math.sqrt(mse)
print("RMSE:", rmse)
mae = mean_absolute_error(y_test, predictions)
print("MAE:", mae)

R2 for train: 1.0
R2 for score: 0.7757405377727026
MSE: 100.19069288010408
RMSE: 10.009530102862175
MAE: 75.51400341053942


In [ ]:
#This time the results are mainly the same